Pre_Accounting-CAPRICORN/Models/Personnel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pre_Accounting_CAPRICORN.Models
{
    public class Personnel
    {
        [Key]
        public int PersonnelID { get; set; }
        public string  PersonnelName { get; set; }
        public string Title { get; set; }

        [Required(ErrorMessage ="*This field is required!")]
        public string Username { get; set; }

        [Required(ErrorMessage = "*This field is required!")]
        public string Password { get; set; }
        public string Authority { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

Pre_Accounting-CAPRICORN/Controllers/PersonnelController.cs
using Pre_Accounting_CAPRICORN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pre_Accounting_CAPRICORN.Controllers
{
    [Authorize]
    public class PersonnelController : Controller
    {
        Context c = new Context();
        // GET: Personnel

        [Authorize(Roles = "A")]
        public ActionResult Index(string search)
        {
            var result = from p in c.Personnels
                         where p.Status == true
                         select p;

            if (!String.IsNullOrEmpty(search))
            {
                result = result.Where(x => x.PersonnelName.Contains(search));
            }
            return View(result.ToList());
        }

        
        public ActionResult NewPersonnel()
        {
            List<SelectListItem> titles = new List<SelectListItem>() {
                new SelectListItem {
                    Text = "Admin", Value = "0"
                },
                new SelectListItem {
                    Text = "Sales Representative", Value = "1"
                }
            };

            ViewBag.titles = titles;
            return View();
        }


        [HttpPost]
        public ActionResult NewPersonnel(Personnel p)
        {
            c.Personnels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeletePersonnel(int id)
        {
            var result = c.Personnels.Find(id);
            if (result != null)
            {
                result.Status = false;
                c.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult BringPersonnel(int id)
        {
            List<SelectListItem> titles = new List<SelectListItem>() {
            new SelectListItem {
             Text = "Admin", Value = "0"
        },
        new SelectListItem {
            Text = "Sales Representative", Value = "1"
        }, };
            ViewBag.titles = titles;
            var result = c.Personnels.Find(id);
            return View("BringPersonnel", result);
        }

        [HttpPost]
        public ActionResult UpdatePersonnel(Personnel p)
        {
            var result = c.Personnels.Find(p.PersonnelID);
            result.PersonnelID = p.PersonnelID;
            result.PersonnelName = p.PersonnelName;
            result.Title = p.Title;
            result.Username = p.Username;
            result.Password = p.Password;
            result.Authority = p.Authority;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PersonnelDetails(int id)
        {
            var result = c.InvoiceItems.Where(x => x.Invoice.PersonnelID == id).ToList();
            return View(result);
        }
    }
}

Pre_Accounting-CAPRICORN/Views/Personnel/BringPersonnel.cshtml
@model Pre_Accounting_CAPRICORN.Models.Personnel
@{
    ViewBag.Title = "BringPersonnel";
}

<h2>Update Personnel</h2>
<br/>
@using (Html.BeginForm("UpdatePersonnel", "Personnel", FormMethod.Post))
{
<div class="form-group">


    @Html.HiddenFor(x => x.PersonnelID)
    @Html.Label("Name")
    @Html.TextBoxFor(x => x.PersonnelName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Title)
    @Html.DropDownListFor(x => x.Title, (List<SelectListItem>)ViewBag.titles, "Choose Title", new { @class = "form-control" })
    <br />
    @Html.Label("Username")
    @Html.TextBoxFor(x => x.Username, new { @class = "form-control" })
    <br />
    @Html.Label("Password")
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <br />
    @Html.Label("Authority")
    @Html.TextBoxFor(x => x.Authority, new { @class = "form-control" })
    <br />
    <button class="btn btn-secondary">Save</button>
</div>
}

Pre_Accounting-CAPRICORN/Views/Personnel/Index.cshtml
@using Pre_Accounting_CAPRICORN.Models;
@model List<Personnel>
@{
    ViewBag.Title = "Index";
}
<br />
@using (Html.BeginForm("Index", "Personnel", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" value="Search" />
}
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Title</th>
        <th>Username</th>
        <th>Password</th>
        <th>Authority</th>
        <th>Status</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
    </tr>
    @foreach (var p in Model)
    {
        <tr>
            <td>@p.PersonnelID</td>
            <td>@p.PersonnelName</td>
            <td>@(p.Title == "0" ? "Admin" : p.Title == "1" ? "Sales Representative" : "not defined")</td>
            <td>@p.Username</td>
            <td>@p.Password</td>
            <td>@p.Authority</td>
            <td>@p.Status</td>
            <td><a href="/Personnel/DeletePersonnel/@p.PersonnelID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Personnel/BringPersonnel/@p.PersonnelID" class="btn btn-success">Update</a></td>
            <td><a href="/Personnel/PersonnelDetails/@p.PersonnelID" class="btn btn-warning">Details</a></td>
        </tr>
    }

</table>

<a href="/Personnel/NewPersonnel/" class="btn btn-secondary">New Personnel</a>

Pre_Accounting-CAPRICORN/Views/Personnel/NewPersonnel.cshtml
@model Pre_Accounting_CAPRICORN.Models.Personnel
@{
    ViewBag.Title = "NewPersonnel";
}

<h2>New Personnel</h2>
<br/>
<form class="form-group" method="post">
    @Html.Label("Name")
    @Html.TextBoxFor(x => x.PersonnelName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Title)
    @Html.DropDownListFor(x => x.Title, (List<SelectListItem>)ViewBag.titles, "Choose Title", new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Username)
    @Html.TextBoxFor(x => x.Username, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Password)
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Authority)
    @Html.TextBoxFor(x => x.Authority, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Status)
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })
    <br />
    <button class="btn btn-secondary">Save</button>
</form>

Pre_Accounting-CAPRICORN/Views/Personnel/PersonnelDetails.cshtml
@using Pre_Accounting_CAPRICORN.Models;
@model List<InvoiceItem>
@{
    ViewBag.Title = "PersonnelDetails";
}

<h2>Personnel Details</h2>

<table class="table table-bordered">
    <tr>
        <td>Row</td>
        <td>Date</td>
        <td>Time</td>
        <td>Product</td>
        <td>Quantity</td>
        <td>Total</td>
        <td>Type</td>
        <td>Customer</td>
    </tr>
    @{ int rowNo = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@(rowNo += 1)</td>
            <td>@item.Invoice.InvoiceDate</td>
            <td>@item.Invoice.InvoiceTime</td>
            <td>@item.Product.ProductName</td>
            <td>@item.Quantity</td>
            <td>@item.Invoice.TotalAmount</td>
            <td>@(item.Invoice.Type == "1" ? "Credit" : item.Invoice.Type == "2" ? "Debt" : "not defined")</td>
            <td>@item.Invoice.Customer.CustomerName</td>
        </tr>
    }
</table>